USE [qltour_new]
GO
BEGIN TRANSACTION
ALTER TABLE [dbo].[FEEDBACK] DROP CONSTRAINT [FK01_FEEDBACK]


ALTER TABLE [dbo].[HOTEL_BOOKING] DROP CONSTRAINT [FK01_HOTEL_BOOKING]


ALTER TABLE [dbo].[INVOICE] DROP CONSTRAINT [FK02_INVOICE]


ALTER TABLE [dbo].[ITINERARY] DROP CONSTRAINT [FK01_ITENERARY]


ALTER TABLE [dbo].[ROSTER] DROP CONSTRAINT [FK02_ROSTER]


ALTER TABLE [dbo].[SHOPPING_CART] DROP CONSTRAINT [FK02_SHOPPING_CART]


ALTER TABLE [dbo].[TRANSPORT_BOOKING] DROP CONSTRAINT [FK01_TRANSPORT_BOOKING]

ALTER TABLE [dbo].[TOUR] DROP CONSTRAINT [PK__TOUR__3213E83F1416058B] WITH ( ONLINE = OFF )


ALTER TABLE [dbo].[TOUR] ADD PRIMARY KEY NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_psTour_637949807949359776] ON [dbo].[TOUR]
(
	[depart_date]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [psTour]([depart_date])


DROP INDEX [ClusteredIndex_on_psTour_637949807949359776] ON [dbo].[TOUR]

ALTER TABLE [dbo].[FEEDBACK]  WITH CHECK ADD  CONSTRAINT [FK01_FEEDBACK] FOREIGN KEY([tour_id])
REFERENCES [dbo].[TOUR] ([id])
ALTER TABLE [dbo].[FEEDBACK] CHECK CONSTRAINT [FK01_FEEDBACK]


ALTER TABLE [dbo].[HOTEL_BOOKING]  WITH CHECK ADD  CONSTRAINT [FK01_HOTEL_BOOKING] FOREIGN KEY([tour_id])
REFERENCES [dbo].[TOUR] ([id])
ALTER TABLE [dbo].[HOTEL_BOOKING] CHECK CONSTRAINT [FK01_HOTEL_BOOKING]


ALTER TABLE [dbo].[INVOICE]  WITH CHECK ADD  CONSTRAINT [FK02_INVOICE] FOREIGN KEY([tour_id])
REFERENCES [dbo].[TOUR] ([id])
ALTER TABLE [dbo].[INVOICE] CHECK CONSTRAINT [FK02_INVOICE]


ALTER TABLE [dbo].[ITINERARY]  WITH CHECK ADD  CONSTRAINT [FK01_ITENERARY] FOREIGN KEY([tour_id])
REFERENCES [dbo].[TOUR] ([id])
ALTER TABLE [dbo].[ITINERARY] CHECK CONSTRAINT [FK01_ITENERARY]


ALTER TABLE [dbo].[ROSTER]  WITH CHECK ADD  CONSTRAINT [FK02_ROSTER] FOREIGN KEY([tour_id])
REFERENCES [dbo].[TOUR] ([id])
ALTER TABLE [dbo].[ROSTER] CHECK CONSTRAINT [FK02_ROSTER]


ALTER TABLE [dbo].[SHOPPING_CART]  WITH CHECK ADD  CONSTRAINT [FK02_SHOPPING_CART] FOREIGN KEY([tour_id])
REFERENCES [dbo].[TOUR] ([id])
ALTER TABLE [dbo].[SHOPPING_CART] CHECK CONSTRAINT [FK02_SHOPPING_CART]


ALTER TABLE [dbo].[TRANSPORT_BOOKING]  WITH CHECK ADD  CONSTRAINT [FK01_TRANSPORT_BOOKING] FOREIGN KEY([tour_id])
REFERENCES [dbo].[TOUR] ([id])
ALTER TABLE [dbo].[TRANSPORT_BOOKING] CHECK CONSTRAINT [FK01_TRANSPORT_BOOKING]

COMMIT TRANSACTION
GO
BEGIN TRANSACTION
ALTER TABLE [dbo].[INVOICE_RECORD] DROP CONSTRAINT [FK01_INVOICE_RECORD]

ALTER TABLE [dbo].[INVOICE] DROP CONSTRAINT [PK__INVOICE__3213E83F8BAEEE00] WITH ( ONLINE = OFF )


ALTER TABLE [dbo].[INVOICE] ADD PRIMARY KEY NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_psInvoice_637949864953962187] ON [dbo].[INVOICE]
(
	[order_date]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [psInvoice]([order_date])


DROP INDEX [ClusteredIndex_on_psInvoice_637949864953962187] ON [dbo].[INVOICE]

ALTER TABLE [dbo].[INVOICE_RECORD]  WITH CHECK ADD  CONSTRAINT [FK01_INVOICE_RECORD] FOREIGN KEY([invoice_id])
REFERENCES [dbo].[INVOICE] ([id])
ALTER TABLE [dbo].[INVOICE_RECORD] CHECK CONSTRAINT [FK01_INVOICE_RECORD]


ALTER TABLE [dbo].[TOUR_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK03_TOUR_DETAIL] FOREIGN KEY([invoice_id])
REFERENCES [dbo].[INVOICE] ([id])
ALTER TABLE [dbo].[TOUR_DETAIL] CHECK CONSTRAINT [FK03_TOUR_DETAIL]

COMMIT TRANSACTION



